;
; File generated by cc65 v 2.19 - Git 0541b65
;
	.fopt		compiler,"cc65 v 2.19 - Git 0541b65"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_handheldModel
	.export		_memoryChipModel
	.export		_dataBitswap
	.export		_opcodeBitswap

.segment	"RODATA"

_handheldModel:
	.byte	$47,$35,$20,$35,$30,$30,$2D,$49,$4E,$2D,$31,$00
_memoryChipModel:
	.byte	$4D,$33,$36,$4C,$30,$52,$37,$30,$35,$30,$54,$30,$00
_dataBitswap:
	.byte	$4E,$4F,$4E,$45,$00
_opcodeBitswap:
	.byte	$36,$2C,$37,$2D,$31,$2C,$32,$00

